### ISSUE TITLE
Add instructions

### ISSUE THREAD

**Issue by tremby** [trapd00r/zsh-syntax-highlighting-filetypes#8]
Please add instructions. I have no idea how to set this up. Any dependencies? What do I put where? Any configuration?

**Comment by diego898** [comment]
Definitely agree

**Comment by trapd00r** [comment]
Just source the script guys.
https://github.com/trapd00r/configs/tree/master/zsh

**Comment by tremby** [comment]
Yes, don't tell us here, put it in the readme!
