### ISSUE TITLE
LS_COLOR naming mismatch

### ISSUE THREAD

**Issue by epaaj** [trapd00r/zsh-syntax-highlighting-filetypes#9]
This project uses ~/.LS_COLORS but the quick install for LS_COLORS stores the file as .dircolors. It would be better if they used the same path/name for an easier installation for people who can't or just don't want to have to look at the source code.

**Comment by trapd00r** [comment]
But we never use a file at all; we extract values from the $LS_COLORS environment variable that will be populated when you run the dircolors command, no matter what the filename is.
